### PR TITLE
Try to fix ZfcUser dependency

### PR DESCRIPTION
**Pull request by Gounlaf**
I'm not sure it's the right to fix it =/

### CODE REVIEW

**Comment by aiolos** [comment]
This fix, or the same as in 'GoalioForgotPassword' seems necessary to use this via composer.

**Comment by adamlundrigan** [comment]
@Gounlaf your change does fix the issue, but IMO it may be better to make the version constraint `1.*` instead of `dev-master`.  @pdobrigkeit could you resolve this issue so that this module is installable when using GoalioForgotPassword 1.x ?

**Comment by pdobrigkeit** [comment]
Will look into it this weekend!

Am 06.06.2014 um 15:19 schrieb "Adam Lundrigan" <notifications@github.com<mailto:notifications@github.com>>:

@Gounlafhttps://github.com/Gounlaf your change does fix the issue, but IMO it may be better to make the version constraint 1.\* instead of dev-master. @pdobrigkeithttps://github.com/pdobrigkeit could you resolve this issue so that this module is installable when using GoalioForgotPassword 1.x ?

##

**Comment by pdobrigkeit** [comment]
See #9

**Pull request closed without merging**
